# Generated by Django 6.0.1 on 2026-01-30 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile_user_upload_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='user_upload_index',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='UserThresholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_percentile', models.FloatField(default=0.75, help_text='Percentile for warning status (0.5-0.95). Equipment above this = Warning.')),
                ('outlier_iqr_multiplier', models.FloatField(default=1.5, help_text='IQR multiplier for outliers (0.5-3.0). Q3 + multiplier*IQR = Critical.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Threshold Settings',
                'verbose_name_plural': 'User Threshold Settings',
            },
        ),
    ]
