# Generated by Django 6.0.1 on 2026-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uploadedfile_user_upload_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='ai_summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
